import Sidebar from "./components/Sidebar";
import localFont from "next/font/local";
import "./globals.css";
import clsx from "clsx";
import { Pacifico } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const advent = Pacifico({
  subsets: ["latin"],
  variable: "--font-adventpro",
  weight: "400",
  style: "normal",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx(
        "text-[#0e2431] bg-[#ececec] dark:text-[#fc3a52] dark:bg-[#0e2431]",
        advent.variable
      )}
    >
      <body className="antialiased max-w-4xl mb-40 flex flex-col md:flex-row mx-4 mt-8 md:mt-20 lg:mt-32 lg:mx-auto">
        <Sidebar />
        <main className="flex-auto min-w-0 mt-6 md:mt-0 flex flex-col px-2 md:px-0">
          {children}
        </main>
      </body>
    </html>
  );
}
